name: Compile MCResourceAnalyzer debug

on: [push, pull_request]
  repository_dispatch:
    types: [build]
  workflow_dispatch:
      inputs:
        name:
          description: 'Run?'
          required: true
          default: 'YES!'
  push:
    branches:
      - 1.17-Test
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Move artifact
      run: |
        mv target/mc-resource-analyzer-1.1.0.jar .
      
    - name: Upload macos artifact
      uses: actions/upload-artifact@v2
      with:
          path: mc-resource-analyzer-1.1.0.jar
